### ISSUE TITLE
Can we get this "on" as an attribute so that it becomes possible to change the language?

### ISSUE THREAD

**Issue by RealKolago** [wolfgang101/include-mastodon-feed#1]
https://github.com/wolfgang101/include-mastodon-feed/blob/63c8df0292d7c0dd3c8a84c4e22b9822abdcd0a4/plugin.php#L414

**Comment by RealKolago** [comment]
Perhaps it is best to be able to change all hard-coded English texts.

**Comment by wolfgang101** [comment]
I agree. Should be all translatable. Can't work on it in the next 2 weeks, but will try to look into i18n once I'm back. Also need to bump supported Wordpress version to 6.2

**Comment by wolfgang101** [comment]
Version 1.7.0 will be available in the Wordpress plugin registry soon. It includes three new text customizations through PHP constants or shortcode attributes.
