### ISSUE TITLE
can't use both limit and excludeReplies options

### ISSUE THREAD

**Issue by kanigsson** [wolfgang101/include-mastodon-feed#2]
When specifying both `limit` and `excludeReplies` option, the `limit` option stops working. My workaround is to stop using the `excludeReplies` option for now.

I took a quick look at the code, and while I'm not fluent in PHP, it seems that the arguments to the Mastodon query are built in such a way that only the last option set among `limit`, `excludeReplies`, `excludeBoosts`, `onlypinned`, `onlymedia` and `tagged` actually ends up in the query.

Could this be fixed please?

**Comment by wolfgang101** [comment]
The code should append all params to an array and then concatenates them into one URL string. I'll do more debugging in the next few days to see if I can find out what's up.

**Comment by wolfgang101** [comment]
Thank you for bringing attention to this issue. Validation of boolean shortcode parameters was broken. A plugin update will be available shortly.

**Comment by wolfgang101** [comment]
Update 1.8.1 is now available

**Comment by kanigsson** [comment]
Thanks a lot for the quick fix!
