### ISSUE TITLE
Multiple occurences of same emoji in a toot

### ISSUE THREAD

**Issue by kanigsson** [wolfgang101/include-mastodon-feed#5]
When an emoji appears multiple times in a toot, only the first occurrence is rendered, for the remaining ones, the emoji text is displayed. I checked [the code](https://github.com/wolfgang101/include-mastodon-feed/blob/e5e3b65181cb6057b24e7aeb08699eabd3c42570/plugin.php#L455), is it possible that `string.replace` only replaces the first occurrence? That would explain it.

**Comment by wolfgang101** [comment]
You are right. Will change string.replace to string.replaceAll in the next release

**Comment by wolfgang101** [comment]
Will be fixed with v1.9.4 which should be available in a few hours from now.

**Comment by kanigsson** [comment]
Thanks a lot for the quick fix! It works now.
